/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_swetasamaddar_dietcam2_NativeClass */

#ifndef _Included_com_example_swetasamaddar_dietcam2_NativeClass
#define _Included_com_example_swetasamaddar_dietcam2_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_swetasamaddar_dietcam2_NativeClass
 * Method:    getMessagefromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swetasamaddar_dietcam2_NativeClass_getMessagefromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
